INSERT INTO departments (dept_name) VALUES ('CS');
INSERT INTO departments (dept_name) VALUES ('MA');
INSERT INTO departments (dept_name) VALUES ('IMGD');
INSERT INTO departments (dept_name) VALUES ('RBE595');

INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 1);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 2);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 3);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 4);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 5);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 6);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 7);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 8);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 9);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 10);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 11);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 12);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 13);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 14);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 15);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 16);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 17);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 18);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 19);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 20);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 23);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 24);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 25);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 28);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 29);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 30);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 31);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 32);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 33);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 34);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 35);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 36);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 37);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 38);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 39);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 40);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 42);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 43);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 44);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 45);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 46);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 47);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 48);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 49);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 50);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 51);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 52);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 53);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 55);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 56);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 57);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 58);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 59);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 60);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 61);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 62);
INSERT INTO course_department_link (course_id, dept_id) VALUES (1, 63);

INSERT INTO course_department_link (course_id, dept_id) VALUES (2, 21);
INSERT INTO course_department_link (course_id, dept_id) VALUES (2, 26);
INSERT INTO course_department_link (course_id, dept_id) VALUES (2, 27);
INSERT INTO course_department_link (course_id, dept_id) VALUES (2, 41);

INSERT INTO course_department_link (course_id, dept_id) VALUES (3, 22);

INSERT INTO course_department_link (course_id, dept_id) VALUES (4, 54);
